<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Shipping Label</title>
    <style>
        body {
            font-family: sans-serif;
        }

        .container {
            width: 100%;
            border: 2px dashed #000;
            padding: 20px;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .row {
            margin-bottom: 20px;
        }

        .label {
            font-weight: bold;
            font-size: 12px;
            color: #555;
        }

        .value {
            font-size: 16px;
            margin-top: 5px;
        }

        .barcode {
            text-align: center;
            margin-top: 30px;
        }

        .footer {
            font-size: 10px;
            text-align: center;
            margin-top: 20px;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>SHIPPING LABEL</h1>
            <p>Order #{{ $order->id }}</p>
        </div>

        <div class="row">
            <div class="label">FROM (SENDER):</div>
            <div class="value">
                {{ $order->vendor->full_name }}<br>
                {{ $order->vendor->email }}
            </div>
        </div>

        <div class="row">
            <div class="label">TO (RECEIVER):</div>
            <div class="value">
                {{ $order->user->full_name }}<br>
                {{ $order->user->email }}
            </div>
        </div>

        <div class="row">
            <div class="label">ITEM DETAILS:</div>
            <div class="value">
                Product: {{ $order->product->name }}<br>
                Price: ${{ number_format($order->amount, 2) }}
            </div>
        </div>

        <div class="barcode">
            <!-- Placeholder for barcode -->
            <div style="background: #000; height: 50px; width: 80%; margin: 0 auto;"></div>
            <p>{{ $order->id }}-{{ time() }}</p>
        </div>

        <div class="footer">
            Generated by USED
        </div>
    </div>
</body>

</html>